const { createClient } = window.supabase;
const cfg = window.BONDHU_CONFIG;
const supabase = createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY);
let currentUser=null,currentProfile=null,selectedImage=null;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function avatar(name='B',url=''){return url?`<img src="${esc(url)}" alt="">`:esc((name||'B').slice(0,1).toUpperCase())}
function initials(name='B'){return (name||'B').slice(0,1).toUpperCase()}
async function getProfile(){if(!currentUser)return null;let {data,error}=await supabase.from('profiles').select('*').eq('id',currentUser.id).single();if(error){console.error(error);return null}currentProfile=data;return data}
function setAvatar(el,name,url){el.innerHTML=avatar(name,url)}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(session){currentUser=session.user;await enterApp()}else enterAuth();supabase.auth.onAuthStateChange(async(_,session)=>{if(session){currentUser=session.user;await enterApp()}else{currentUser=null;currentProfile=null;enterAuth()}})}
function enterAuth(){$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}
async function enterApp(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');await getProfile();const p=currentProfile||{};$('#topUsername').textContent=p.username||currentUser.email.split('@')[0];setAvatar($('#topAvatar'),p.username,p.avatar_url);setAvatar($('#composerAvatar'),p.username,p.avatar_url);if(p.role==='admin')$('#adminPanel').classList.remove('hidden');await loadStories();await loadFeed()}
async function login(){const identity=$('#loginIdentity').value.trim(),password=$('#loginPassword').value;if(!identity||!password)return toast('Enter your login details.');let email=identity;if(!identity.includes('@')){const {data,error}=await supabase.from('profiles').select('email').eq('username',identity.toLowerCase()).maybeSingle();if(error||!data?.email)return toast('Username not found.');email=data.email}const {error}=await supabase.auth.signInWithPassword({email,password});if(error)toast(error.message);else toast('Welcome back to Bondhu.')} 
async function signup(){const username=$('#signupUsername').value.trim().toLowerCase(),email=$('#signupEmail').value.trim(),password=$('#signupPassword').value;if(!/^[a-z0-9_\.]{3,24}$/.test(username))return toast('Username: 3–24 letters, numbers, _ or .');if(password.length<8)return toast('Use at least 8 characters.');const {data,error}=await supabase.auth.signUp({email,password,options:{data:{username}}});if(error)return toast(error.message);if(data.user)toast(data.session?'Account created.':'Check your email to confirm your account.')} 
async function logout(){await supabase.auth.signOut();toast('Logged out.')}
async function loadStories(){const row=$('#storiesRow');row.innerHTML='<div class="story"><div class="avatar">＋</div><small>Your story</small></div>';const {data}=await supabase.from('profiles').select('id,username,avatar_url').limit(8);(data||[]).forEach(x=>row.insertAdjacentHTML('beforeend',`<div class="story"><div class="avatar">${avatar(x.username,x.avatar_url)}</div><small>${esc(x.username)}</small></div>`))}
async function loadFeed(){const feed=$('#feed');feed.innerHTML='<div class="muted">Loading your feed…</div>';const {data,error}=await supabase.from('posts').select('id,content,image_url,created_at,user_id,profiles(username,avatar_url)').order('created_at',{ascending:false}).limit(30);if(error){feed.innerHTML='<div class="empty-state glass"><h2>Feed needs one setup step</h2><p>Run the included schema.sql in Supabase SQL Editor, then refresh Bondhu.</p></div>';return}feed.innerHTML=(data||[]).map(post=>postHtml(post)).join('')||'<div class="empty-state glass"><h2>Your feed is quiet.</h2><p>Be the first to share something with your Bondhu.</p></div>';await wirePostActions()}
function postHtml(p){const author=p.profiles?.username||'Bondhu';return `<article class="post glass" data-id="${p.id}"><div class="post-head"><div class="avatar">${avatar(author,p.profiles?.avatar_url)}</div><div class="meta"><b>${esc(author)}</b><small>${new Date(p.created_at).toLocaleString()}</small></div>${p.user_id===currentUser?.id?'<button class="post-menu delete-post">•••</button>':''}</div><p>${esc(p.content||'')}</p>${p.image_url?`<img class="post-media" src="${esc(p.image_url)}" alt="Post image">`:''}<div class="post-actions"><button class="like-post">♡ Like</button><button>◌ Comment</button><button>↗ Share</button></div></article>`}
async function wirePostActions(){$$('.delete-post').forEach(b=>b.onclick=async e=>{const id=e.currentTarget.closest('.post').dataset.id;if(confirm('Delete this post?')){const {error}=await supabase.from('posts').delete().eq('id',id);if(error)toast(error.message);else loadFeed()}});$$('.like-post').forEach(b=>b.onclick=async e=>{const id=e.currentTarget.closest('.post').dataset.id;const {data}=await supabase.from('post_likes').select('post_id').eq('post_id',id).eq('user_id',currentUser.id).maybeSingle();if(data){await supabase.from('post_likes').delete().eq('post_id',id).eq('user_id',currentUser.id);e.currentTarget.textContent='♡ Like'}else{await supabase.from('post_likes').insert({post_id:id,user_id:currentUser.id});e.currentTarget.textContent='♥ Liked'}})}
async function createPost(){const content=$('#postText').value.trim();if(!content&&!selectedImage)return toast('Write something or choose a photo.');let image_url=null;if(selectedImage){const ext=selectedImage.name.split('.').pop();const path=`${currentUser.id}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('post-media').upload(path,selectedImage,{upsert:false});if(error)return toast('Image upload: '+error.message);image_url=supabase.storage.from('post-media').getPublicUrl(path).data.publicUrl}const {error}=await supabase.from('posts').insert({user_id:currentUser.id,content,image_url});if(error)toast(error.message);else{$('#postText').value='';selectedImage=null;$('#photoInput').value='';toast('Posted to Bondhu.');loadFeed()}}
async function loadPeople(target,query=''){let q=supabase.from('profiles').select('id,username,avatar_url,bio').neq('id',currentUser.id).limit(18);if(query)q=q.ilike('username',`%${query}%`);const {data}=await q;target.innerHTML=(data||[]).map(p=>`<div class="person glass"><div class="avatar">${avatar(p.username,p.avatar_url)}</div><b>${esc(p.username)}</b><small>${esc(p.bio||'Bondhu community member')}</small><button class="secondary follow-btn" data-id="${p.id}">Follow</button></div>`).join('')||'<div class="muted">No people found.</div>';$$('.follow-btn').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('follows').insert({follower_id:currentUser.id,following_id:b.dataset.id});if(error)toast(error.code==='23505'?'Already following.':error.message);else{b.textContent='Following';toast('Following.')}})}
async function loadProfile(){const p=currentProfile||await getProfile();$('#profileCard').innerHTML=`<div class="profile-cover"></div><div class="profile-info"><div class="avatar">${avatar(p?.username,p?.avatar_url)}</div><div><h2>${esc(p?.username||'Bondhu')}</h2><span class="muted">@${esc(p?.username||'bondhu')}</span></div></div><div class="profile-bio"><p>${esc(p?.bio||'Welcome to my Bondhu profile.')}</p></div>`;const {data}=await supabase.from('posts').select('id,content,image_url,created_at,user_id,profiles(username,avatar_url)').eq('user_id',currentUser.id).order('created_at',{ascending:false});$('#profilePosts').innerHTML=(data||[]).map(postHtml).join('')||'<div class="empty-state glass"><p>No posts yet.</p></div>';await wirePostActions()}
async function loadNotifications(){const {data}=await supabase.from('notifications').select('*').eq('user_id',currentUser.id).order('created_at',{ascending:false}).limit(30);$('#notificationList').innerHTML=(data||[]).map(n=>`<div class="notification"><b>${esc(n.title||'Bondhu')}</b><div class="muted">${esc(n.body||'You have a new notification.')}</div><small class="muted">${new Date(n.created_at).toLocaleString()}</small></div>`).join('')||'<div class="notification">No notifications yet.</div>'}
function switchScreen(screen){$$('.screen').forEach(x=>x.classList.add('hidden'));$('#screen-'+screen).classList.remove('hidden');$$('[data-screen]').forEach(x=>x.classList.toggle('active',x.dataset.screen===screen));$('#screenLabel').textContent=screen.toUpperCase();$('#pageTitle').textContent={home:'Good to see you.',explore:'Discover your people.',friends:'Your circle.',messages:'Stay close.',groups:'Find your community.',notifications:'Nothing slips by.',profile:'Your Bondhu profile.',settings:'Make it yours.'}[screen]||'Bondhu';if(screen==='explore')loadPeople($('#exploreGrid'));if(screen==='friends')loadPeople($('#friendsGrid'));if(screen==='profile')loadProfile();if(screen==='notifications')loadNotifications()}
$$('[data-auth]').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.auth!=='login');$('#signupForm').classList.toggle('hidden',b.dataset.auth!=='signup')});$('#loginBtn').onclick=login;$('#signupBtn').onclick=signup;$('#logoutBtn').onclick=logout;$$('[data-toggle]').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.toggle);i.type=i.type==='password'?'text':'password'});$('#forgotBtn').onclick=async()=>{const email=$('#loginIdentity').value.trim();if(!email.includes('@'))return toast('Enter your email to reset password.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.href});toast(error?error.message:'Reset link sent.')};$('#postBtn').onclick=createPost;$('#photoBtn').onclick=()=>$('#photoInput').click();$('#photoInput').onchange=e=>{selectedImage=e.target.files[0]||null;if(selectedImage)toast(selectedImage.name+' selected.')};$('#mobileCreate').onclick=()=>{switchScreen('home');$('#postText').focus()};$$('[data-screen]').forEach(b=>b.onclick=()=>switchScreen(b.dataset.screen));$('#topProfile').onclick=()=>switchScreen('profile');$('#themeBtn').onclick=()=>document.body.classList.toggle('light');$('#settingsTheme').onclick=()=>document.body.classList.toggle('light');$('#settingsReset').onclick=()=>$('#forgotBtn').click();$('#exploreSearch').oninput=e=>loadPeople($('#exploreGrid'),e.target.value);$('#adminStats').onclick=()=>toast('Admin role active. Add your admin dashboard module as needed.');
boot();
